# Liste von Pflege Weiterbildungen anzeigen -> OK 200
http://localhost:8080/app/weiterbildung/

###

# Eine ausgewählte Weiterbildung in Pflege Weiterbildung anzeigen -> OK 200
GET http://localhost:8080/app/weiterbildungAnzeigen/6a36a29d-a6d9-4a71-887c-f4eb2856b18d/undefined HTTP/1.1
Content-Type: application/json

{
	"id_w": "6a36a29d-a6d9-4a71-887c-f4eb2856b18d"
}

###

# Eine Weiterbildung löschen -> OK 200
DELETE http://localhost:8080/app/weiterbildung/1e4089ab-ab7e-42c6-b1bf-64969b03f3b3 HTTP/1.1
Content-Type: application/json

{
	"id_w": "1e4089ab-ab7e-42c6-b1bf-64969b03f3b3"
}
