# Auswertung Mitarbeiter anzeigen -> OK 200
GET http://localhost:8080/app/auswertungMitarbeiter/28a00ba3-182a-4c39-bc5c-379d4d43d09e/undefined HTTP/1.1
Content-Type: application/json

{
	"id_w": "28a00ba3-182a-4c39-bc5c-379d4d43d09e"
}
